### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by hey-red** [julian-r/file-windows#2]
Can you write guide how to build file with cmake? 
I'm trying to build it with "Visual Studio 15 2017", but no luck.

**Comment by julian-r** [comment]
Do you have more specific details? What is you procedure? What are your steps?

**Comment by KrishVikram** [comment]
Hi, any instructions or steps as to how to build these binaries on Windows using Visual Studio? It would be of much help, thanks!

**Comment by KrishVikram** [comment]
To be precise, this .dll when u try to load it in Python, throws a VCRUNTIME140.DLL missing pop-up on OS<Win 10. Is there a way to avoid/overcome this by building it again?
