### ISSUE TITLE
Error "file: (null) (No such file or directory)"

### ISSUE THREAD

**Issue by drshajul** [julian-r/file-windows#21]
Any file type, same error

**Comment by toiletbril** [comment]
`file` looks for `magic.mgc` in `../share/misc/` by default, and shows that message when it fails to find it.

1. You can explicitly specify magic database files using `file -m <path to .mgc>`
1. If you don't want to use `-m`, you can put `magic.mgc` in `../share/misc/` relative to your `file.exe`. It could look like this:
```
binaries/
├── file.exe
└── libmagic.dll
share/
└── misc/
    └── magic.mgc
```
