### ISSUE TITLE
Unable to build using VS2010 in windows

### ISSUE THREAD

**Issue by KrishVikram** [julian-r/file-windows#4]
I'm facing a lot of compiler issues when trying to build using cmake and visual studio 2010.

1. error C2061: syntax error : identifier 'mode_t' [C:\Krishna\File-Magic\file-windows\libmagic.vcxproj]
2. file\src\apprentice.c(457): error C2037: left of 'flags' specifies undefined struct/union 'magic_set' [C:\Krishna\File-Magic\file-windows\libmagic.vcxproj]

Looks like the VS compiler is not able to read the unix-style code. Is there any special compiler switch or something that is necessary to avoid these errors? 

Thanks.

**Comment by KrishVikram** [comment]
Build steps used:
git clone https://github.com/julian-r/file-windows.git
cd file-windows
git submodule init 
git submodule update

1. cmake .
2. msbuild mysolutionfile.sln

**Comment by julian-r** [comment]
sorry vs2010 is not intendet do be supported you need to use the same vsc version as used for the python interpreter...
